# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a6b4dcae80ea40214f42c09744b23acdd4b48e19750a3ab1111ad872c28929bafcb6f5ce508850bd83725c60603e96ba6a41e6ee539dd9076bccc3dd0a4dfbf7

test:
  secret_key_base: ed8c4462c0fbb690a06ff3884213c7e1038d854df8744e26a8bdc1a129863ce53f81173325e8a3efba2d131ace18dda9ea2d2542b7ff0aecc8ed78522db2c572

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
